### ISSUE TITLE
Navrbar design 

### ISSUE THREAD

**Issue by xq-ankit** [mohitahlawat2001/Loco-Musica#1]
I would like to work on the navbar and fix the design also the no of item weather in the cart or the recipe  is beside the icon that doesn't look standard that could be fixed

**Comment by mohitahlawat2001** [comment]
sure i will assign you this , when make pr post video or photo of nav bar

**Comment by Rossville** [comment]
I would like to work on issue. @mohitahlawat2001 can you assign this to me?

**Comment by mohitahlawat2001** [comment]
@Rossville you can also work on this , but whoever navbar look more good , i will merge it

**Comment by Rossville** [comment]
Thanks @mohitahlawat2001

**Comment by mohitahlawat2001** [comment]
not any progress
