### ISSUE TITLE
Update search bar

### ISSUE THREAD

**Issue by Aneeshaik** [mohitahlawat2001/Loco-Musica#10]
Updating the restaurants on the fly according to user  when user typing any name in the search bar instead of only when he presses the search button. Also, search button is remaining as grayed out even when user typing in search bar.
I can contribute to this issue. Please assign me to this under hacktoberfest. Thank You!

**Comment by mohitahlawat2001** [comment]
if you can add debouncing to it , you can do it , let me know

**Comment by Aneeshaik** [comment]
Sure! I can add

**Comment by mohitahlawat2001** [comment]
ok i will assign it to you ,
make sure post video , when make pr ,

> also please star repo ⭐

**Comment by Aneeshaik** [comment]
Sure!
