### ISSUE TITLE
Improve Footer Design

### ISSUE THREAD

**Issue by Mihirjataniya** [mohitahlawat2001/Loco-Musica#13]
![image](https://github.com/user-attachments/assets/3ea86ab9-4a75-4aad-954d-bd879378dec2)
The current footer design can be enhanced to improve the overall user experience. I have a few suggestions that could make the footer more engaging and functional.
The "Welcome Guest!" and email address should be moved from the footer to the navbar. This will clean up the footer and make the welcome message more visible and logically placed with navigation elements.
It would be great to include social media links (e.g., Twitter, Instagram, LinkedIn, etc.) in the footer. This will make it easier for users to connect with the brand on other platforms.
I suggest adding a creative tagline or slogan that reflects the  project's theme
I kindly request adding the `hacktoberfest2024` tag to this issue.

**Comment by Afsar16** [comment]
hey please assign me this issue, i will work on it

**Comment by Mihirjataniya** [comment]
I would like to work on this

**Comment by mohitahlawat2001** [comment]
both of you make pr whoever design is best i will merge it 

make sure you star ⭐  this repo and follow on github

**Comment by mohitahlawat2001** [comment]
@Mihirjataniya are you working on this as afsar submitted , i can wait one more day , if you are still wokring

**Comment by mohitahlawat2001** [comment]
production failed , you need to redo

**Comment by Mihirjataniya** [comment]
can u just explain the procedure so that it doesnt fail the production

**Comment by mohitahlawat2001** [comment]
Fetch  again , made pr again, it might work , i revert 2 commits back , so
it becomes working again
