### ISSUE TITLE
Issue: Search bar is not responsive in small screens

### ISSUE THREAD

**Issue by basavarajakj** [mohitahlawat2001/Loco-Musica#16]
I have noticed this issue in all small screen devices. Could you please fix it.

![image](https://github.com/user-attachments/assets/24185f3d-39b9-4f7c-af3f-a647e39d49ac)

If u need to fix this feel free to assign me. I will start to work.

Thanks! Cheers🥂
Happy coding

**Comment by mohitahlawat2001** [comment]
sure , 
make sure you star repo and follow me on github

**Comment by namansharma3007** [comment]
@basavarajakj please assign issue to me
