### ISSUE TITLE
[FIX] : Make the design compatible with different devices

### ISSUE THREAD

**Issue by mohitahlawat2001** [mohitahlawat2001/Loco-Musica#2]
- using tailwindcss for this , 
- right now look good only for desktop, 

**[do not change theme only make if compatible for different size of screen]**

**Comment by mahenoorsalat** [comment]
I will look on this matter it's better if you assign me this issue :) thank you :)

**Comment by mohitahlawat2001** [comment]
sure i will assign you this , when make pr post video or photo of work 


> _please mark star ⭐  if you liked repo_

**Comment by mohitahlawat2001** [comment]
did you make change

**Comment by mahenoorsalat** [comment]
- fixing issue #27
