### ISSUE TITLE
Responsiveness can be improve 

### ISSUE THREAD

**Issue by lightning-sagar** [mohitahlawat2001/Loco-Musica#23]
hey i can improve the responsiveness, please assign me
and if u go to RecipeStore the footer is not fixed..... assign me pls

**Comment by mohitahlawat2001** [comment]
sure i will assign it to you, star repo ⭐ and follow on github

**Comment by lightning-sagar** [comment]
@mohitahlawat2001 hey i have added a pr kindly check it out
