### ISSUE TITLE
User can increase the number of items in cart by Menu page itself

### ISSUE THREAD

**Issue by sujal1256** [mohitahlawat2001/Loco-Musica#24]
The issue is when a user adds a food item to the cart, then again clicking on Add to Cart gives this message which should be improved
![image](https://github.com/user-attachments/assets/cce6649f-e008-47ff-a506-3420abba22a2)

So the user should be able to increase or decrease the quanitity of food item from Menu page itself

The task will include 

-  Increment and Decrement of Food Items will be done and stored in redux store
-  The Add to Cart button will be there if the food item is not in the redux store

**Comment by sujal1256** [comment]
I am already working on this issue, please assign this to me

**Comment by mohitahlawat2001** [comment]
sure i will assign it to you, star repo ⭐ and follow on github
