### ISSUE TITLE
Add Categories for food

### ISSUE THREAD

**Issue by Laikokwui** [mohitahlawat2001/Loco-Musica#26]
Add category such as Lunch, Breakfast, Branch, Dinner, Supper for the food.

**Comment by mohitahlawat2001** [comment]
sure i will assign it to you, star repo ⭐  and follow on github

**Comment by Laikokwui** [comment]
@mohitahlawat2001 how do i add more data return from the api?

**Comment by mohitahlawat2001** [comment]
can explore api , you find data there
