### ISSUE TITLE
Add Hover Effect on Navbar

### ISSUE THREAD

**Issue by mahenoorsalat** [mohitahlawat2001/Loco-Musica#28]
**Description:**
- I would like to work on adding a hover effect to the navbar links. 

- Currently, the navbar lacks this interactivity, which could enhance user experience by providing visual feedback when users hover over the links.

**Proposed Changes:**

- [X] I plan to add a style change (such as a color change, underline, or background color) on navbar links when hovered over.
- [X] I'll make sure that the hover effect is accessible and provides sufficient contrast for all users.
- [X] I will verify that the hover effect works seamlessly on both desktop and mobile views.

**This enhancement will improve the usability of the navbar and create a more engaging interface for users.**

Please assign me this issue .. 

**I am looking forward to your response and am eager to contribute to this matter.**

Thank you :)

Ping @mohitahlawat2001

**Comment by mohitahlawat2001** [comment]
You can start working, I will assign when I get back to my pc , make sure
you star repo and follow on GitHub
