### ISSUE TITLE
[FEAT] Scrollbar Styles

### ISSUE THREAD

**Issue by MishraTanishq619** [mohitahlawat2001/Loco-Musica#29]
I think we haven't given customised styles to our scrollbar.
We should custom our scrollbar as per our theme.

I want to work on this myself.
Please assign it to me and add tags for hacktoberfest-2024.

**Comment by mohitahlawat2001** [comment]
You can start working, I will assign when I get back to my pc , make sure
you star repo and follow on GitHub

**Comment by MishraTanishq619** [comment]
Sure Thanks
