### ISSUE TITLE
[FIX] : Make api work for different location 

### ISSUE THREAD

**Issue by mohitahlawat2001** [mohitahlawat2001/Loco-Musica#3]
- add geo location for fetch coordinate and then add them to api , then show result 
- handle case when coordinate on api doesn't give result (api is only used in indian loaction)

**Comment by prayag78** [comment]
Hello @mohitahlawat2001 
I would like to work on this issue.

**Comment by mohitahlawat2001** [comment]
sure i will assign you this , when make pr post video or photo of this working fine or not,


> _please mark star ⭐  if you liked repo_

**Comment by Rossville** [comment]
@mohitahlawat2001 Can you please assign this issue to me ? I have one question should the location apart from Indian one be also fetched ?

**Comment by mohitahlawat2001** [comment]
it is already assigned @Rossville

**Comment by mohitahlawat2001** [comment]
done #8
