### ISSUE TITLE
Should prompt to login page when user tries to add food items to cart when not logged in.

### ISSUE THREAD

**Issue by Aakansha-Chavan** [mohitahlawat2001/Loco-Musica#35]
Here, when any user who is not logged in tries to add food items to the cart, they should be prompted to log in page before proceeding. The system should redirect them to the log in page to ensure authenticated access to cart functionality.
![image](https://github.com/user-attachments/assets/8ae620c6-53b8-4622-bb12-193b7e13076d)

Can you please assign me this issue? I am new to open source but I will try to resolve this issue

**Comment by mohitahlawat2001** [comment]
there is no need for this , login is not necessary, as there is no login function rigthnow
