### ISSUE TITLE
Improve food cards' design

### ISSUE THREAD

**Issue by Rikir-M** [mohitahlawat2001/Loco-Musica#37]
Hey, I've noticed that the food cards' UI can be improved, like adding link to the card, not to just the food name and better transition effects for better user experience. I'd like to work on that. Can you assign it to me? Thanks.

**Comment by mohitahlawat2001** [comment]
@Rikir-M 
 i assign you this issue , post video or photo of site , when you make Pr

> make sure you star ⭐ repo if you like and follow on github

**Comment by Rikir-M** [comment]
@mohitahlawat2001 
Ok, noted. I will. Thanks for assigning me this issue.

**Comment by mohitahlawat2001** [comment]
any progress ?

**Comment by Rikir-M** [comment]
hello, yes. I'm working on it

**Comment by Kruthik111** [comment]
I think this one and issue #55 both are the same issue. Assign this to me, once i complete these you can close both the issues
