### ISSUE TITLE
[BUG] : Login form not responsive on smaller screens

### ISSUE THREAD

**Issue by ShobhitPatra** [mohitahlawat2001/Loco-Musica#42]
Description:
The login form is not displaying correctly on smaller screens . 

Current Behavior:
The login form elements (username/email, password fields, login button) are not properly aligned or scaled

Expected Behavior:
The login form should adjust to the screen size and display properly on smaller screens.

Input fields and buttons should stack or resize accordingly without overlap or truncation.
![Screenshot from 2024-10-05 09-35-00](https://github.com/user-attachments/assets/96860b6a-a9a5-46de-b09f-0c90bf0920b3)

**Comment by ShobhitPatra** [comment]
would like to work on it

**Comment by mohitahlawat2001** [comment]
#43 #44 @ShobhitPatra i am assigning it to you, make sure you star ⭐ repo and follow on github
make one pr for all of this

**Comment by Anurag-singh-thakur** [comment]
@mohitahlawat2001  hey could you assign it to me please ..i assure you that i can do it within a time period of 24 hours
