### ISSUE TITLE
[BUG] : Searchbar Not Responsive

### ISSUE THREAD

**Issue by ShobhitPatra** [mohitahlawat2001/Loco-Musica#44]
Description:
The search bar is not displaying . On medium to small  screen sizes, the search bar may appear too large, be cut off, or become misaligned with other elements of the page, affecting usability and overall user experience.

![Screenshot from 2024-10-05 09-37-12](https://github.com/user-attachments/assets/ef4d5f84-ad6d-431b-880a-790ace68d02a)

**Comment by ShobhitPatra** [comment]
would like to work on it

**Comment by mohitahlawat2001** [comment]
@ShobhitPatra i am assigning it to you, make sure you star ⭐ repo and follow on github
