### ISSUE TITLE
Fix food card sizing on the homepage for responsiveness

### ISSUE THREAD

**Issue by sarwar-jahin-port** [mohitahlawat2001/Loco-Musica#55]
I have recently set up the project, and the responsiveness of the homepage caught my attention. As you can see in the screenshot, the food cards are not properly sized, which affects the layout. I want to fix this issue to ensure the cards are displayed consistently across different screen sizes.
![image](https://github.com/user-attachments/assets/a552a9b9-8cec-42f1-be33-e53b0d25654e)

**Comment by mohitahlawat2001** [comment]
Sure you can work on this , I will assign you, when I get back to my pc

**Comment by sarwar-jahin-port** [comment]
Okay.

**Comment by sarwar-jahin-port** [comment]
@mohitahlawat2001
