### ISSUE TITLE
Frontend: Food details sidebar always be in fixed position

### ISSUE THREAD

**Issue by rajmanna-dev** [mohitahlawat2001/Loco-Musica#58]
### UI Enhancement

Right now the food details sidebar scrolling with right side menu section.

### Secreenshots
![Screenshot 2024-10-07 162706](https://github.com/user-attachments/assets/49f719b9-b6ec-46f1-8065-6a40f4b6302e)

### Additional

I would love to contribute on this repo.

**Comment by mohitahlawat2001** [comment]
i assigned it to you, 

> make sure you star ⭐  repo and follow on github
