### ISSUE TITLE
Duplicate Food Item Added to Cart

### ISSUE THREAD

**Issue by HMSagar2701** [mohitahlawat2001/Loco-Musica#6]
When a user adds the same food item to the cart more than once, it shows up multiple times in the cart. This shouldn't happen. The cart should either increase the quantity of the item or not allow adding it again.

**Comment by mohitahlawat2001** [comment]
may be user want more than one time

**Comment by HMSagar2701** [comment]
![image](https://github.com/user-attachments/assets/16a6f149-fd80-4cae-8842-8c9362fd6462)
we can increase the count of quantity instead of multiple entries please check the image

**Comment by mohitahlawat2001** [comment]
sure , i will assigned it to you, 

> make sure star ⭐  repo

**Comment by HMSagar2701** [comment]
Hi @mohitahlawat2001, I have implemented this can I raise PR for this now ?
