### ISSUE TITLE
Improving the card's UI

### ISSUE THREAD

**Issue by Bhavishya2601** [mohitahlawat2001/Loco-Musica#61]
When we hover on the text of the food card, the text has a different hover effect, which doesn't look good and the card is toggling between white and pink, that doesn't pleasant to watch
I would like to change it to a single which gives it a more professional look

Can you Assign this issue to me under Hactoberfest

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by Bhavishya2601** [comment]
done
pls add the hactoberfest tag
