### ISSUE TITLE
Enhance Navbar: Make Sticky and Improve Appearance

### ISSUE THREAD

**Issue by Abhi-Jeeet** [mohitahlawat2001/Loco-Musica#62]
The current navbar is basic and lacks modern design features. This issue aims to enhance the user experience by making the navbar sticky at the top of the page and improving its overall appearance.

Please assign it to me and mark it as hactoberfest.

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by Abhi-Jeeet** [comment]
I have star the repo and also followed you on github.
