### ISSUE TITLE
Improve Footer and make it more animated

### ISSUE THREAD

**Issue by anmol-284** [mohitahlawat2001/Loco-Musica#66]
I want to work on the footer section, want to improve its animations.
please assign this to me and also add hacktoberfest label too

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by anmol-284** [comment]
Starred it now.

**Comment by mohitahlawat2001** [comment]
do whole step , you done only half

**Comment by anmol-284** [comment]
sorry but what is left to do, can you please tell me ?

**Comment by anmol-284** [comment]
Please accept it.
