### ISSUE TITLE
[BUG]: Search button need to fix

### ISSUE THREAD

**Issue by Priyanshu-su30** [mohitahlawat2001/Loco-Musica#68]
The search button is going out of the search tab
Assign me this task and I'll fix it.

![Screenshot (224)](https://github.com/user-attachments/assets/60fbf727-1f94-40d3-8225-fa0c7c9a2749)

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by Priyanshu-su30** [comment]
@mohitahlawat2001 Kindly add hacktoberfest labels
