### ISSUE TITLE
Google Authentication for Login and Signup

### ISSUE THREAD

**Issue by GnautSpace** [mohitahlawat2001/Loco-Musica#7]
Hi, I’d like to contribute by adding Google authentication for the login and signup process. This would include checking if the user already exists in the database and logging them in, or signing them up if they don't. If the database hasn't been set up yet, I can help with that as well.

Would it be okay if I work on this? Let me know if you have any preferences or specific guidelines!

**Comment by mohitahlawat2001** [comment]
yes you can work on this currenty on authentication

**Comment by GnautSpace** [comment]
Thanks for assigning me! I'll keep you updated on the same.
