### ISSUE TITLE
real-time password strength analysis

### ISSUE THREAD

**Issue by yalsik86** [mohitahlawat2001/Loco-Musica#70]
Implementation of real-time password strength analysis feature for login page.

@mohitahlawat2001 please assign me this issue and label as hacktoberfest.

**Comment by yalsik86** [comment]
@mohitahlawat2001 i have starred the repo

**Comment by mohitahlawat2001** [comment]
> and follow on github , giving hacktoberfest tag after this step


>

**Comment by yalsik86** [comment]
@mohitahlawat2001 followed
