### ISSUE TITLE
Enhancement: Improve Backend Security and Code Quality

### ISSUE THREAD

**Issue by Abhilash107** [mohitahlawat2001/Loco-Musica#72]
Description:
- Enhance backend security by addressing password handling, JWT management, and response structures.

Identified Issues:
- Incorrect Status Code: Using 404 instead of 409 for existing users and should use 401 for incorrect login credentials.
- Insecure Password Handling: Plaintext password comparison.
- Case Sensitivity: Inconsistent field casing.
- JWT Error Handling: Missing try-catch around jwt.verify().

Suggested Fixes:
- Update Status Code: Use 401 Unauthorized for unauthenticated requests and 409 Conflict if an user already exists.
- Use bcrypt: Hash passwords before saving in DB.
- Add Error Handling: Wrap jwt.verify() in a try-catch block.

Where to Check:
- Status Code Fixes: controllers/control.js
- Password Handling: controllers/control.js
- JWT Middleware: middlewares/auth.js

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by Abhilash107** [comment]
@mohitahlawat2001  Thank you for considering me for this task. However, I would prefer not to work on it.
