### ISSUE TITLE
issue with  Card details UI ,attached Image of the same

### ISSUE THREAD

**Issue by agnijeetsharma** [mohitahlawat2001/Loco-Musica#73]
I have attached the image of the small bug in the UI.
Which is not good for the user experience.
Navbar and card details are coinciding and side card component not even completely visible.
I can fix this issue and can provide better UI.
@mohitahlawat2001 kindly assign me this issue under hacktoberfest-2024

![Screenshot 2024-10-11 225042](https://github.com/user-attachments/assets/8ab68baa-7cba-49dc-aa17-8af949be85f7)

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by agnijeetsharma** [comment]
@mohitahlawat2001 done

**Comment by agnijeetsharma** [comment]
@mohitahlawat2001 can i start working on it.
Kindly label as hacktoberfest

**Comment by agnijeetsharma** [comment]
@mohitahlawat2001 merge my previous Pr ,in which i have added dark Mode functionality and Kindly label that hacktoberfest
i am working on this also
thanks
