### ISSUE TITLE
[ENHANCEMENT]: SEND MAIL ON CONTACT US FORM

### ISSUE THREAD

**Issue by ash956901** [mohitahlawat2001/Loco-Musica#74]
Right now upon submitting deatils of the contact us form , it doesnt do anything i would like to add contact us form to actually contact the author , therefore would like to setup mail functionality for the same .

<img width="1440" alt="Screenshot 2024-10-12 at 12 53 54 AM" src="https://github.com/user-attachments/assets/347d67e2-e87c-4ad7-b986-c51c83915280">

**Comment by ash956901** [comment]
Please assign this issue to me to get it done asap and please add the hacktober tag to it too .. @mohitahlawat2001 sir

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by ash956901** [comment]
@mohitahlawat2001 sir it is becoming very difficult even after setting up all the env to get the project up in local enviorenment , i would recommend adding it in a docker container , so as to not have conflicting dependencies and other similar issue in local enviorenment , right now while i was trying to run your code , it hit me with lots of conflicting , outdated dependcies, and malloc errors. So if anyone can make the project into a container it would be better and easier for all of us to contribute . For this , we can open an issue and see if anyone comes up to do the same till production and see if it deploys perfectly or not. Will like devops people to come ahead and do this .

**Comment by ash956901** [comment]
Have opened an issue for the same
