### ISSUE TITLE
[ENHANCEMENT]: ADD DOCKER AND MAKE IT LIGHT

### ISSUE THREAD

**Issue by ash956901** [mohitahlawat2001/Loco-Musica#77]
Hey everyone,

I’ve been encountering several issues while trying to run the project locally—mainly dependency conflicts, outdated packages, and malloc errors, even after setting up everything as required. It’s been pretty tricky to get everything working smoothly.

To make contributing easier and avoid these environment issues, I think it would be beneficial to containerize the project using Docker. This would ensure that everyone works in a consistent environment without worrying about dependency conflicts or setup problems.

It would be great if someone from the DevOps side could step in to help set this up. We can also test the Docker setup for production to make sure it works perfectly.

Looking forward to your thoughts on this!

Cheers

**Comment by vrushabhgawas14** [comment]
I can dockerize this project, assign me so I can work on this issue.

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step
