### ISSUE TITLE
[feature] Add Restaurant and Food Menu

### ISSUE THREAD

**Issue by shiv-sk** [mohitahlawat2001/Loco-Musica#82]
Currently, the project lacks a dedicated Restaurant model, which is necessary to store specific restaurant information, as well as a Food Menu model to store menu items related to a particular restaurant

solution:
models : Restaurant , food menu model
controllers : crud on both models
user : adding roles using enum [user , admin , owner]

restaurant model and food menu model
restaurant name , address , location , comment 
food name , image , rate/price 

if u swish to consider this issue please assign me under hacktoberfest label

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by shiv-sk** [comment]
@mohitahlawat2001 bro what about hacktoberfest tag

**Comment by mohitahlawat2001** [comment]
> i assigned it to you
> 
> > make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

read this

**Comment by shiv-sk** [comment]
@mohitahlawat2001 ok bro I will do

**Comment by shiv-sk** [comment]
@mohitahlawat2001 bro I just followed and gave the star

**Comment by shiv-sk** [comment]
@mohitahlawat2001 hey bro actually I have completed my backend development and I want two pr one for all backend code and second one is integrating the server response on front side like showing all restaurants and food menu of a specific restaurant is that I am allowed to send 2 pr's or else I need send only in one pr looking forward to ur reply

**Comment by mohitahlawat2001** [comment]
one pr fine
