### ISSUE TITLE
broken link: LICENSE 

### ISSUE THREAD

**Issue by Saiharitha3** [mohitahlawat2001/Loco-Musica#84]
broken link for LICENSE in Readme file

![image](https://github.com/user-attachments/assets/664ec1a2-9f95-4e31-b5f8-a976f887d0a8)

**Comment by Saiharitha3** [comment]
Hi @mohitahlawat2001 please assign this issue if you feel useful and add hacktoberfest label

**Comment by mohitahlawat2001** [comment]
i assigned it to you 

> make sure you star repo ⭐  and follow on github , giving hacktoberfest tag after this step

**Comment by Saiharitha3** [comment]
okay, thank you!

**Comment by Saiharitha3** [comment]
please review PR #85
